version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 6969:6969
    volumes:
      - ./src:/app/src

  dbadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  # redis:
  #   image: redis
  #   ports:
  #     - '6379:6379'
  #   restart: always

volumes:
  pgadmin-data:
